---
- name: Exercise to create 5 new users using loop
  hosts: all
  tasks: 
  - name: Create 5 new users using loop
    win_user:
      name: "{{ item.name }}"
      group: "{{ item.grp }}"
      description: "{{ item.desc }}"
      state: Present
    loop:
    - { name: 'Pickahu', grp: 'Thursday', desc: 'Electric Pokemon'} #Old format
    - { name: 'Bulbasur', grp: 'Thursday', desc: 'Plant Pokemon'} #Old format
    - { name: 'Rapidash', grp: 'Thursday', desc: 'Fire Pokemon'} #Old format
    - { name: 'Goldeen', grp: 'Thursday', desc: 'Water Pokemon'} #Old format
    - { name: 'Dragonair', grp: 'Thursday', desc: 'Dragon Pokemon'} #Old format

    # NEW / Block Format - can define information in multiple lines
    - name: 'Squirtle'
      grp: 'Thursday'
      desc: 'Water Pokemon'


